// <auto-generated />
using System;
using Infrastructure.SqlServer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(InvestimentosDbContext))]
    [Migration("20251120171642_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ProdutoInvestimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<int>("PrazoMaximoMeses")
                        .HasColumnType("int")
                        .HasColumnName("PrazoMaximoMeses");

                    b.Property<int>("PrazoMinimoMeses")
                        .HasColumnType("int")
                        .HasColumnName("PrazoMinimoMeses");

                    b.Property<decimal>("Rentabilidade")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("Rentabilidade");

                    b.Property<string>("Risco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Risco");

                    b.Property<long>("TipoId")
                        .HasColumnType("bigint")
                        .HasColumnName("IdTipoProdutoInvestimento");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("ProdutoInvestimento", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.TipoProdutoInvestimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("TiposProdutoInvestimentos");
                });

            modelBuilder.Entity("Domain.Entities.ProdutoInvestimento", b =>
                {
                    b.HasOne("Domain.Entities.TipoProdutoInvestimento", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tipo");
                });
#pragma warning restore 612, 618
        }
    }
}
